version: 2

sources:
  - name: ATL
    database: SANDBOX_DB
    schema: GOWTHAMV_ATLSRVDB_DBT
    tables: &tables_list
      - name: BINTYPES
        # identifier: ATLSRVDB_BINTYPES
  
  - name: CHI
    database: SANDBOX_DB
    schema: GOWTHAMV_CHISRVDB_DBT
    tables: *tables_list

  - name: DVN
    database: SANDBOX_DB
    schema: GOWTHAMV_DVNSRVDB_DBT
    tables: *tables_list

